#4 Onboarding
DeveloperAcademy-POSTECH/MC3-Team1-SixTech pull request #8
Opened 2023-07-14 08:00 UTC by Oreo-Mcflurry

## What I Did!

* [ ] #4 
<img width="255" alt="스크린샷 2023-07-14 16 35 19" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/assets/96654328/c097a744-126a-44d5-a5fc-61db9f68c130">

폰트 파일을 추가했습니다. 사용은 .font(.custom("폰트파일명", size: 사이즈)) 로 사용하면 됩니다. 적용이 안된다면 info.plist를 확인해보시면 될 것 같아요. 제가 올리는 파일에는 적용된 상태입니다.
또한, 런치스크린도 따로 스크린샷을 올리진 않겠지만, info.plist LaunchScreen에 적용시켜두었습니다. 

https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/blob/7fc51bb66cc1498fece841857fb377143e7e17a1/SixTech/ButtonStyle/ButtonStyle.swift#L28-L40
DefaultButton Style을 작성했습니다.  여기서 이슈가, 버튼 스타일에 Bool값을 가져와 .disabled을 먹여도, 적용이 되지 않습니다. 그래서 만약 disable이 필요한 경우 버튼 스타일을 먹인 후 .disabled를 통해 적용시켜주시면 되고, 필요 없다면 false를 기본으로 넣어주시면 됩니다.

https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/blob/7fc51bb66cc1498fece841857fb377143e7e17a1/SixTech/Extension/ColorExtension.swift#L8-L32
ColorExtension을 작성했고, 사용은 다른 컬러들 사용하는 것 처럼 사용하시면 됩니다.

https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/blob/7fc51bb66cc1498fece841857fb377143e7e17a1/SixTech/View/Onboarding/OnBoardingView.swift#L8-L37
온보딩 화면이 전부 이런식인데, 버튼과 맨 위의 text의 크기는 같지만 중간의 이미지 크기가 전부 달라 높이가 전부 달라버리는 문제점이 있었습니다. padding등 여러 방법을 시도해봤지만, 기기대응 등의 이슈를 생각해서 GeometryReader를 이용해 해결했는데, 더 좋은 아이디어 있다면 제시 부탁드리겠습니다. 또한 GIF의 경우 Pakage를 설치해서 사용했습니다. SwiftUIGIF를 import시키고 사용하는 pakage입니다. 레퍼런스에 원본 github링크 남겨놓겠습니다.

## Review Point

* ButtonStyle에 disable이 안먹여져서 스타일을 적용할때마다 조건이나 false를 넘겨줘야한다는 단점이 있는데, 더 좋은 해결 방안이 있는지, 아이디어 부탁드립니다
* Onboarding파일에서 버튼과 Text의 위치를 맞추기 위해 Geometry를 사용했는데, 괜찮은 선택이였는지에 대해 의견을 묻고 싶습니다.

## Reference

https://kkannsoon2.tistory.com/2
https://github.com/globulus/swiftui-gif
https://stackoverflow.com/questions/59169436/swiftui-buttonstyle-how-to-check-if-button-is-disabled-or-enabled
-> 잘 안됨

2023-07-14 08:45 UTC, 220v-K requested changes
머스크 수고했습니다~

첫 PR과 첫 코드리뷰군여 히히.

2023-07-14 08:45 UTC, 220v-K commented on SixTech/Extension/ColorExtension.swift
> +extension Color {
#colorLiteral 문법을 이용해 처리하면, XCode 상에서 코드에서 바로바로 색이 표시되어 그렇게 하는 것도 깔끔할 것 같아요!
다만, hex Code가 표시되지는 않아 주석으로 옆에 hex Code를 달아 같은 색이 존재하는 지 확인하는 용도로 사용하면 되지 싶습니다.

2023-07-14 08:45 UTC, 220v-K commented on SixTech/ButtonStyle/ButtonStyle.swift
> +struct DefaultButton: ButtonStyle {
ButtonStyle을 Custom해서 사용하는 거 좋은 것 같아요!
저는 중복되는 Component가 존재할 때, 보통 View 자체를 Return하는 함수를 만들어 사용하는 경우가 잦은데,
뭐가 더 좋은 방법일지는 잘 모르겠어요. (다만 버튼이 아닌 다른 component라면 buttonstyle 등으로 처리할 수 없으니 Struct나 Function을 새로 만드는 쪽이 나을 거 같네요.)

우선 상기한 방법의 예시를 MC2 프로젝트에서 발췌하여 보여드리겠습니다!
```swift
/// CardGenerateViews에서 자주 사용되는 하단 버튼 탬플릿을  추가
/// - Parameters:
///   - title: 버튼의 title
///   - disableCondition: 버튼을 disable 할 수 있는 조건 (bool)
///   - action: 버튼을 눌렀을때의 액션
/// - Returns: Button을 return.
/// - 이후 네비게이션 구현시, 똑같은 lable을 사용하는 NavigationLink Component를 아래에 하나 더 구현해서, 뷰 전환되는 구간의 버튼은 해당 네비게이션 링크로 대체 요망
///
func cardGenerateViewsButton(title:String, disableCondition: Bool, action: @escaping ()->Void ) -> some View {
    return Button(action: action){
        RoundedRectangle(cornerRadius: 10)
           .fill(disableCondition ? Color(disabledNextButtonColor) : mainAccentColor )
           .frame(width: 321, height: 48)
           .overlay(
               Text(title)
                   .foregroundColor(.white)
                   .font(.system(size: 17, weight: .semibold))
           )
    }.disabled(disableCondition)
}
```

2023-07-14 08:45 UTC, 220v-K commented on SixTech/Extension/ColorExtension.swift
> +// 폰트는 .font(.custom("TheJamsilOTF3Regular", size: 24))처럼 사용하고, "" 안에 이름은 파일명으로 할 것.
폰트에 대한 파일이 없어서 여기에 작성합니다.

폰트를 쓸 때마다 이렇게 String값을 넣어서 처리하면 좀 불편할 것 같고, enum을 활용해서 간결하게 처리할 수 있도록 변경하면 좋을 것 같아요.

아래는 예시입니다.

```swift
extension Font {
    enum MainFonts {
        case Thin
        case Light
        case Regular
        // ...

        var value: String {
            switch self {
            case .Thin:
                return "TheJamsilOTF1Thin"
            case .Light:
                return "TheJamsilOTF2Light"
            case .Regular:
                return "TheJamsilOTF3Regular"
            }
        }
    }

    static func mainFont(_ type: MainFonts, size: CGFloat = 17) -> Font {
        return .custom(type.value, size: size)
    }
}
```

2023-07-14 08:45 UTC, 220v-K commented on SixTech/View/Onboarding/OnBoarding2View.swift
> +            .position(x:geometry.size.width/2, y:geometry.size.height/2)
여기 혹시 geometryReader를 이용해서 position을 강제로 조정해줘야 했던 이유가 있을까요?

2023-07-14 11:34 UTC, Oreo-Mcflurry commented on SixTech/View/Onboarding/OnBoarding2View.swift
> +            .position(x:geometry.size.width/2, y:geometry.size.height/2)
GeometryReader사용시 중앙정렬이 아닌, 위와 왼쪽으로 강제 정렬이 되기에, position으로 정렬을 해줘야 합니다.

2023-07-14 11:34 UTC, Oreo-Mcflurry commented on SixTech/Extension/ColorExtension.swift
> +// 폰트는 .font(.custom("TheJamsilOTF3Regular", size: 24))처럼 사용하고, "" 안에 이름은 파일명으로 할 것.
바로 채택하겠습니다

2023-07-14 11:36 UTC, Oreo-Mcflurry commented on SixTech/ButtonStyle/ButtonStyle.swift
> +struct DefaultButton: ButtonStyle {
저도 ButtonView자체를 return하는거로 구상하긴 했었는데, 버튼 스타일을 처음 써보기 위해 써본것도 있긴 했습니다만,, 저도 뭐가 좋을지 모르겠네요. 다른 분의 의견도 들어보고 싶습니다

2023-07-14 11:37 UTC, Oreo-Mcflurry commented on SixTech/Extension/ColorExtension.swift
> +extension Color {
#colorLiteral에 대한 지식이 없어서 잘 몰랐는데, 이번기회에 한번 공부해보겠습니다.

2023-07-14 18:55 UTC, 220v-K commented on SixTech/Extension/ColorExtension.swift
> +// 폰트는 .font(.custom("TheJamsilOTF3Regular", size: 24))처럼 사용하고, "" 안에 이름은 파일명으로 할 것.
좋아요 요건 수정해서 이 PR에 달아주세요 ^ㅁ^

2023-07-14 18:56 UTC, 220v-K commented on SixTech/View/Onboarding/OnBoarding2View.swift
> +            .position(x:geometry.size.width/2, y:geometry.size.height/2)
GeometryReader를 사용하지 않고 Spacer() 등으로 조정할 수 없나요?
GeometryReader 사용 이유가 궁금해요!

2023-07-15 05:08 UTC, Oreo-Mcflurry commented on SixTech/View/Onboarding/OnBoarding2View.swift
> +            .position(x:geometry.size.width/2, y:geometry.size.height/2)
Spacer, padding등 여러방법을 시도해보니 가운대의 image의 크기가 전부 달라 Text와 Button의 위치가 제각각이 되더라구요, frame으로 height값을 매겨줘야 깔끔하게 되다보니 기기별로 최대한 깔끔하게 맞추려고 GeometryReader를 사용하게 되었습니다. 코드가 그렇게 깔끔하진 않은데,,

2023-07-15 05:35 UTC, Oreo-Mcflurry commented on SixTech/Extension/ColorExtension.swift
> +// 폰트는 .font(.custom("TheJamsilOTF3Regular", size: 24))처럼 사용하고, "" 안에 이름은 파일명으로 할 것.
![스크린샷 2023-07-15 14 33 07](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/assets/96654328/f2d11e4c-e373-4628-bcba-fb8e6d98a4ce)
여기다간 어케 코드 다는질 몰라서 일단 사진으로 첨부했고, 작성해서 커밋 후 푸시 날렸습니다.
사용법은 다음과 같습니다.
-> .font(.Jamsil.regular.font(size: 24))
좋은 의견 감사합니다 젝무

2023-07-17 14:22 UTC, 220v-K commented on SixTech/View/Onboarding/OnBoarding2View.swift
> +            .position(x:geometry.size.width/2, y:geometry.size.height/2)
앗 그렇군요. 알겠습니다 !

2023-07-17 14:22 UTC, 220v-K commented on SixTech/Extension/ColorExtension.swift
> +// 폰트는 .font(.custom("TheJamsilOTF3Regular", size: 24))처럼 사용하고, "" 안에 이름은 파일명으로 할 것.
넵 좋아요!

2023-07-18 20:28 UTC, JJunghyunY reviewed
주말간 기획 다시해보고 제꺼하느라 리뷰가 늦었네요
코드리뷰 제대로 해본적없어서 어색한데 이래저래 코멘트 남겨봤어요
코드 잘 짜주셨네요 보기좋아요~(LGTM)

2023-07-18 20:28 UTC, JJunghyunY commented on SixTech/ButtonStyle/ButtonStyle.swift
> +    }
여기 상수 너무 많이박혀있는것같아요
특히 frame같은 사이즈는 이 함수로 Button을 만드는 View에서 받아오는게 좋지않을까요?
기기마다 버튼 느낌이 다를것같아요 특히 WatchOS에서는 해당 ButtonStyle 못써용

2023-07-18 20:28 UTC, JJunghyunY commented on SixTech/ButtonStyle/ButtonStyle.swift
> +    @State var isdisable: Bool
여기부분 Binding쓰고 위에서 State로 상태 전달해주는게 어떨까요~?

2023-07-18 20:28 UTC, JJunghyunY commented on SixTech/OnboardingGIF.gif
이건 누가만든건가요 ㅋㅋ

2023-07-18 20:28 UTC, JJunghyunY commented on SixTech/ButtonStyle/ButtonStyle.swift
> +struct DefaultButton: ButtonStyle {
버튼스타일 쓰는거 나쁘지 않다고 생각해요~

2023-07-18 20:28 UTC, JJunghyunY commented on SixTech/View/Onboarding/OnBoardingView.swift
> +import SwiftUIGIF
써드파티 안쓰고는 불편하긴 하죠,, 찾아보니까 WebView로 그나마 gif파일 어떻게 하던데
SwiftGIF 그냥 진행할까요

2023-07-19 01:25 UTC, Oreo-Mcflurry commented on SixTech/OnboardingGIF.gif
귀여워여 ㅋㅋㅋㅋ

2023-07-19 01:25 UTC, Oreo-Mcflurry commented on SixTech/View/Onboarding/OnBoardingView.swift
> +import SwiftUIGIF
GIF하나만 들어가면 패키지나 임포트 안시키고 어케어케 하면 될거같긴 한데... 뭐가 좋을질 모르겠네요

2023-07-19 01:27 UTC, Oreo-Mcflurry commented on SixTech/ButtonStyle/ButtonStyle.swift
> +    @State var isdisable: Bool
ㅠㅠ 저도 고민이 많은데,,, 그냥 버튼 스타일 자체에서 disabled가 안먹혀서 버튼 스타일이 아니라 뷰로 다시 만들까 고민이 있네요.

2023-07-19 01:29 UTC, Oreo-Mcflurry commented on SixTech/ButtonStyle/ButtonStyle.swift
> +    }
그쵸,,, 이것두 근데 어찌되었든 버튼스타일이 아니라 커스텀 버튼으로 다시 만들까 고민이 있어 어찌될까 싶네요

2023-07-19 04:31 UTC, 220v-K approved these changes

2023-07-19 07:00 UTC, JJunghyunY approved these changes

2023-07-19 07:02 UTC, Jhwan2 approved these changes
<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/assets/82885362/d0ca7fc3-13d6-49a5-a30b-2d5b541dedd4" width="300" height="220">

### 진행시켜!

2023-07-19 07:02 UTC, merged